cqfd: display ini parsing error
This patch displays the convertion of the cqfdrc ini file into shell
function.

This may help users and developpers to understand the reason of
failure.

diff --git a/cqfd b/cqfd
--- a/cqfd
+++ b/cqfd
@@ -80,6 +80,7 @@ cfg_parser() {
 	ini[0]="" # remove first element
 	ini[${#ini[*]} + 1]='}'    # add the last brace
 	if ! eval "$(echo "${ini[*]}")" 2>/dev/null; then # eval the result
+		echo -e "Parsing error:\e[31;1m${ini[*]}\e[0m" 1>&2
 		die "$1: Invalid ini-file!"
 	fi
 
